development:
  clients:
    default:
      database: ceps
      username:
      password:
      hosts:

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: ceps
      username:
      password:
      hosts:

  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  clients:
    default:
      database: ceps
      username:
      password:
      hosts:

  options:
    raise_not_found_error: false