development:
  clients:
    default:
      database: "<%= ENV['MONGODB_DATABASE'] %>"
      username: "<%= ENV['MONGODB_USERNAME'] %>"
      password: "<%= ENV['MONGODB_PASSWORD'] %>"
      hosts:
        - "<%= ENV['MONGODB_HOST'] %>:<%= ENV['MONGODB_PORT'] %>"

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: "<%= ENV['MONGODB_DATABASE'] %>"
      username: "<%= ENV['MONGODB_USERNAME'] %>"
      password: "<%= ENV['MONGODB_PASSWORD'] %>"
      hosts:
        - "<%= ENV['MONGODB_HOST'] %>:<%= ENV['MONGODB_PORT'] %>"

  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  clients:
    default:
      database: "<%= ENV['MONGODB_DATABASE'] %>"
      username: "<%= ENV['MONGODB_USERNAME'] %>"
      password: "<%= ENV['MONGODB_PASSWORD'] %>"
      hosts:
        - "<%= ENV['MONGODB_HOST'] %>:<%= ENV['MONGODB_PORT'] %>"

  options:
    raise_not_found_error: false