development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

  options:
    raise_not_found_error: false