development:
  sessions:
    default:
      database: ceps
      username: ceps
      password: password
      hosts:
        - dbh63.mongolab.com:27637
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: ceps_test
      hosts:
        - localhost:27017
  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  sessions:
    default:
      database: ceps
      username: ceps
      password: password
      hosts:
        - ceps.ccec.unf.edu:27017
  options:
    raise_not_found_error: false