development:
  clients:
    default:
      database: ceps
      username:
      password:
      hosts:
        - localhost:27017

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: ceps_test
      hosts:
        - localhost:27017

  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  clients:
    default:
      database: ceps
      username: ceps
      password: password
      hosts:
        - localhost:27017

  options:
    raise_not_found_error: false