development:
  clients:
    default:
      database: ceps
      username: ceps_user
      password: Fast_100
      hosts:
        - ds015770.mlab.com:15770

  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: ceps_test
      username: ceps_user
      password: falkirk1
      hosts:
        - ds015770.mlab.com:15770

  options:
    read: primary
    max_retries: 1
    retry_interval: 0
    raise_not_found_error: false

production:
  clients:
    default:
      database: ceps
      username: ceps_user
      password: Fast_100
      hosts:
        - ds015770.mlab.com:15770

  options:
    raise_not_found_error: false