development:
  sessions:
    default:
      database: ceps
      username: ceps
      password: password

      hosts:
        - dbh63.mongolab.com:27637

      options:

test:
  sessions:
    default:
      database: ceps_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: ceps
      username: ceps
      password: password

      hosts:
        - localhost:27017

      options: